### ISSUE TITLE
Any good first issues + implementation of Sequential? 

### ISSUE THREAD

**Issue by Ashvith** [ankane/tensorflow-ruby#8]
Is there anything that a newbie can help with implementing? And can we start with adding a "Discussions" tab for the repo? We could discuss about the implementation of Sequential, which I am a little confused about, because I've checked out the Python repo, and I see that the Sequential model is a child class of the Functional API.
`class Sequential(functional.Functional):`
Would it be wise to do the same ?

**Comment by ankane** [comment]
Hey @Ashvith, things are currently on-hold since the C API doesn't support gradients for eager tensors yet.
