### ISSUE TITLE
How install tensorflow in Linux?

### ISSUE THREAD

**Issue by 0xtrzy** [ankane/tensorflow-ruby#9]
I'm not have **brew**. How install tensorflow. I have one but **gem** not see my instalation.
Meybe normall add whole source code of _tflow_?

```
/home/user/.gem/ruby/2.7.0/gems/ffi-1.15.0/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'tensorflow': tensorflow: cannot open shared object file: No such file or directory. (LoadError)
Could not open library 'libtensorflow.so': libtensorflow.so: cannot open shared object file: No such file or directory
```

**Comment by ankane** [comment]
Hey @0xtrzy, check out the [installation instructions](https://github.com/ankane/tensorflow-ruby#tensorflow-installation) in the readme.

**Comment by Ashvith** [comment]
@0xtrzy it looks like you have to install [Tensorflow](https://www.tensorflow.org/install/lang_c) first.
